### PR TITLE
ENH: Adds bulk_delete methods

### LINKED ISSUE #64: Add a bulk_delete method to each backend to speed up delete_expired_responses()
Currently, all delete methods remove a single item at a time. `remove_expired_responses()` would be several times faster if each backend had a database-specific bulk delete method.

### PR DESCRIPTION
**Pull request by kirkhansen**
Closes #64

- [ ] make sure tests are sufficient
- [ ] add documentation for changes

### CODE REVIEW

**Comment by JWCook** [comment]
Thanks for picking this up!

**Comment by kirkhansen** [comment]
I was looking over the user guide and noticed a reference to `remove_expired_responses` which I think is actually the `delete_expired_responses`. https://aiohttp-client-cache.readthedocs.io/en/latest/user_guide.html#removing-expired-responses

Should `delete_expired_responses` support an expire_after kwarg, and do you want me to update the docs there quick to `s/remove_expired_responses/delete_expired_responses`?

**Comment by JWCook** [comment]
> I was looking over the user guide and noticed a reference to `remove_expired_responses` which I think is actually the `delete_expired_responses`. https://aiohttp-client-cache.readthedocs.io/en/latest/user_guide.html#removing-expired-responses
> 
> Should `delete_expired_responses` support an `expire_after` kwarg, and do you want me to update the docs there quick to `s/remove_expired_responses/delete_expired_responses`?

Good catch! That must have been a copy-paste error from the requests-cache docs. Just update the docs for now; we can wait on supporting `expire_after` for that until someone needs it.

**Comment by JWCook** [comment]
LGTM. Thanks a lot for the contribution!

**Comment by JWCook** [comment]
Your changes are now in 0.6.0.dev0.

**Pull request merged**
